#!/bin/bash

USAGE="USAGE: checkout UCM_SERVER[e.g. http://localhost/idc] USER PASSWORD DOC_NAME"
OUT_FILE=/dev/null

# Check the required params
if [ "$#" -lt "4" ]
then
	echo $USAGE
	exit 1
fi
if [ "$1" = "" ]
then
	echo "No UCM server defined. Ensure SVR vaiable is being set."
	echo $USAGE
	exit 1
fi
SVR=$1
if [ "$2" = "" ]
then
	echo "No UCM logon defined. Ensure USR vaiable is being set."
	echo $USAGE
	exit 1
fi
USR=$2
if [ "$3" = "" ]
then
	echo "No UCM password defined. Ensure you pass a sysadmin password in from the command line"
	echo $USAGE
	exit 1
fi
PASS=$3
if [ "$4" = "" ]
then
	echo "No UCM password defined. Ensure you pass a sysadmin password in from the command line"
	echo $USAGE
	exit 1
fi
DOC_NAME=$4

curl -u $USR:$PASS -F "IdcService=CHECKOUT_BY_NAME" -F "dDocName=$DOC_NAME" $SVR/idcplg >> $OUT_FILE 
echo "Checked out the file..."
