#!/bin/bash
# 
# License: This code is licensed as per the LICENSE file
# included.
#
# Script to tail the console log file for a UCM server instance on
# a remote machine.
# It assumes that you are ussing public/private keys to
# access your servers over SSH.
# Certain environment variables need to be deinfed that set
# the home dir for the the UCM installation.
# An example of how to set these up can be seen in the demo_servers
# file contained within this folder.
#
#
# Usage:
# idc <server name>
#
# Todo:
# - Add checking that SERVERS and UCM_HOME has been set
# - Check that the user has passed in the correct command line params
#
#
# Author: Kris Foster kristian.foster@gmail.com
#

eval "UCM_HOME=\$$(echo $1'_UCM_HOME')"
echo 'UCM Home Dir: '$UCM_HOME
echo '. ~/.profile; cd '$UCM_HOME'/etc; pwd; tail -f ./log;' | ssh $1

